#!/bin/bash

mkdir hashlists
cd hashlists

for ((i=0;i<=9;i++)); do
	wget https://virusshare.com/hashes/VirusShare_0000$i.md5 &
done

for ((i=10;i<=99;i++)); do
	wget https://virusshare.com/hashes/VirusShare_000$i.md5 &
done

for ((i=100;i<=312;i++)); do
	wget https://virusshare.com/hashes/VirusShare_00$i.md5 &
done



